name: PR Approves Check Example Job

on:
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  onSubmit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: 'approvesCheck'
        with:
          requiredApprovesAmount: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "PR is approved!"
        if: steps.approvesCheck.outputs.isApproved == 'true'

